.Dd April 1, 2009
.Dt SHOWPATH 1 LOCAL
.Os Generic Unix
.
.Sh NAME
.Nm showpath
.Nd manageably edit path
.
.Sh SYNOPSIS
.Nm showpath
.Op Fl t Ar type | Fl e Ar ENV_NAME
.Op Fl s Ar separator
.Ar path_entry ...
.
.Sh DESCRIPTION
The showpath tool writes a string suitable for use as a path
to stdout.
The string is constructed by combining the path entries given on
the command line, in order, with duplicates pruned.
.
.Pp
A path_entry containing the path separator is treated as a fragment
of a path and is broken down into its constituent parts by splitting
at the separators; these parts will then be added as if they were
named separately on the command line.
.
.Pp
A path_entry beginning with
.Ql \&%
is a
.Em short name ,
and will be expanded to a set of path entries that are then added
as if they were named separately on the command line.  The short
names currently supported are
.Ql %current ,
which expands to the entries in the current path (taken from the
environment), and
.Ql %pwd ,
which expands to the current directory.
Allowing additional short names to be defined (by system and/or
user configuration files) is a feature scheduled for implementation
in the near future.
.
.Pp
If a path entry (including one that is the result of short name
expansion or path splitting) begins with
.Ql \&~ ,
the
.Ql \&~
will be expanded to the current value of
.Ev $HOME .
.
.Pp
A path_entry prefixed with
.Ql \&^
will have shortname expansion or path splitting done as normal,
and then the set of path entries it expands to will be
.Em removed
from the path being constructed instead of being added to it.
Entries that have been removed may be re-added, and will be placed
at the end of the path (this is exactly the same handling as anything
else not in the path under construction).
.
.Pp
The following options are available:
.Bl -tag -width flag
.
.It Fl e Ar ENV_NAME
Specifies an environment variable name to look up for the expansion of
.Ql %current .
.
.It Fl s Ar separator
Specifies the path separator.
The separator must be a single character and defaults to
.Ql \&: .
.
.It Fl t Ar type
Specifies a pre-configured path type.
Valid types are currently compiled in; making them configurable (by system
and/or user configuration) is a feature scheduled for implementation in
the near future.
.Pp
Currently known types are:
.Bl -tag -compact
.It Li exec
(for
.Ev $PATH )
.It Li man
(for
.Ev $MANPATH )
.El
.
.Pp
The
.Fl t
option currently only provides a shorthand for an equivalent use of the
.Fl e
option.
Adding short names for sets of path entries is a feature scheduled
for implementation in the near future; when this happens, specifying
a type will also select a set of short names based on the type.
.
.El
.Pp
The
.Fl t
and
.Fl e
options are mutually exclusive, and at most one of either can be specified.
Specifying neither is equivalent to specifying
.Bk -words
.\" When being processed with troff, this Ql expands to a call to Li, which
.\" generates a "cancels effect" warning since its first arg is a macro.
.\" But Ql does its thing on the the '-t exec' as desired (with nroff it
.\" quotes it), which is why it's there.   --DV
.Ql Fl t Li exec .
.Ek
.
.Sh FILES
None yet.
.
.Sh EXAMPLES
Put
.Pa ~/bin
at the beginning of
.Ev $PATH ,
or move it to the beginning if it's already in there somewhere:
.Bd -literal -offset indent -compact
PATH="\*(gashowpath ~/bin %current\*(ga"
.Ed
.
.Pp
Put
.Pa ~/bin
at the end of
.Ev $PATH ,
or move it to the end if it's already in there somewhere:
.Bd -literal -offset indent -compact
PATH="\*(gashowpath %current ^~/bin ~/bin\*(ga"
.Ed
.
.Pp
Tell gcc to use header and library files from Macports,
without clobbering existing values of the environment
variables used:
.Bd -literal -offset indent -compact
C_INCLUDE_PATH="\*(gashowpath -eC_INCLUDE_PATH %current /opt/local/include\*(ga"
LIBRARY_PATH="\*(gashowpath -eLIBRARY_PATH %current /opt/local/lib\*(ga"
export C_INCLUDE_PATH LIBRARY_PATH
.Ed
.
.Pp
Invoke a setup script that adds entries to
.Ev $PATH ,
but force new entries to go at the end instead of the beginning:
.Bd -literal -offset indent -compact
oldpath="$PATH"
\&. /path/to/setup/script
PATH="\*(gashowpath "$oldpath" %current\*(ga"
.Ed
.
.Sh HISTORY
The MFCF environment at the University of Waterloo has a tool by
the same name with similar behavior, which simplifies configuring
paths for the local environment.
.
.Pp
This version does
.Em not
handle its arguments in a manner compatible with the UW version.
.
.Sh AUTHORS
.An "Dave Vandervies" Aq dj3vande@eskimo.com
.
.Pp
.An -nosplit
With contributions from
.An "Stephen Paul Weber" Aq singpolyma@singpolyma.net
.
.Sh BUGS
Empty entries are discarded by strtok when breaking down a path
fragment into its constituent parts.
If you really want an empty path entry, give yourself a whack with
the cluestick and then say
.Bk -words
.Ql showpath %current \&"" .
.Ek
.
.Pp
The
.Li ~ Ns -expansion
done by
.Nm
prevents any path entry in the output from starting with
.Ql \&~ .
.Pp
Send new bug reports to
.Aq dj3vande@eskimo.com .
